### ISSUE TITLE
[Executing] -2014: API-key format invalid

### ISSUE THREAD

**Issue by VandrerenErik** [yonathan95/BinanceTradingBot#11]
![image](https://user-images.githubusercontent.com/54407345/117614969-fd533e80-b160-11eb-92d7-eb3f7dd4d204.png)
Hello,

I'm having problem above. I know I'm most likely doing something wrong. Can anyone help me with this please?

Note: I have double checked the usual stupid human made mistake such copying a space or similar things.

**Comment by yonathan95** [comment]
HI, 
it seems that you didn't paste the binance api key as described in the readme, please make sure you do so.

**Comment by Bharath-Deva** [comment]
Hi, 
I'm having the same problem, still couldn't able to solve it.
