### ISSUE TITLE
Proper Read.Me

### ISSUE THREAD

**Issue by ELHARAKA** [yonathan95/BinanceTradingBot#2]
First of all Thanks for this tool.

I have setup everything as mentioned in your Readme Doc. but how to run this tool there where i get no clue.
Im not familiar with Java, im running Ubuntu WSL in Win10. so how can i run this?

Thank you

**Comment by yonathan95** [comment]
Hi, first of all thank you for asking this question.
After you setup the things mentioned in the readme you have two options:
1. Use the example strategies we created which are explained in the readme file. For example, if you want to use the rsi strategy with candle interval of one minute on symbol 'btcusdt', all you have to do is run the code and then type:
```
activate strategy default, btcusdt, 1m, rsi
```
2.   Create a new strategy or edit an existing one and adjust the code to your new strategy.

If you have more questions please ask :).

Yonathan

**Comment by ELHARAKA** [comment]
Thank you :)
