### ISSUE TITLE
web socket not connecting

### ISSUE THREAD

**Issue by gizmobin** [yonathan95/BinanceTradingBot#8]
The below is repeated in the console.  Tracing the code and it appears that the web socket is not connecting and the watchdog is timing out as a result.  I have downloaded binance-java-sdk and used the web socket tests successfully, so the socket is accessible from my computer and is working properly.

I've gone through the docs and I'm likely missing something, just not sure what.  Your assistance is appreciated, thanks!

[main] INFO com.binance.client.impl.WebSocketConnection - [Sub] Connection [id: 0] created for ***Candlestick for LTCUSDT***
[main] INFO com.binance.client.impl.WebSocketConnection - [Sub][0] Connecting...
[OkHttp https://fstream.binance.com/...] INFO com.binance.client.impl.WebSocketConnection - [Sub][0] Connected to server
[pool-2-thread-1] WARN com.binance.client.impl.WebSocketConnection - [Sub][0] No response from server
[pool-2-thread-1] WARN com.binance.client.impl.WebSocketConnection - [Sub][0] Reconnecting after 15 seconds later
[OkHttp https://fstream.binance.com/...] ERROR com.binance.client.impl.WebSocketConnection - [Sub][0] Unexpected error: Socket closed
com.binance.client.exception.BinanceApiException: Unexpected error: Socket closed
[pool-2-thread-1] INFO com.binance.client.impl.WebSocketConnection - [Sub][0] Connecting...
[pool-2-thread-1] INFO com.binance.client.impl.WebSocketConnection - [Sub][0] Connecting...
[OkHttp https://fstream.binance.com/...] INFO com.binance.client.impl.WebSocketConnection - [Sub][0] Connected to server
[OkHttp https://fstream.binance.com/...] INFO com.binance.client.impl.WebSocketConnection - [Sub][0] Connected to server
[pool-2-thread-1] WARN com.binance.client.impl.WebSocketConnection - [Sub][0] No response from server
[pool-2-thread-1] WARN com.binance.client.impl.WebSocketConnection - [Sub][0] Reconnecting after 15 seconds later
[OkHttp https://fstream.binance.com/...] ERROR com.binance.client.impl.WebSocketConnection - [Sub][0] Unexpected error: Socket closed

**Comment by yonathan95** [comment]
Hi,
I will appreciate it if you will add the following information:
1. Did it happen to you every time you ran the code? if not how many times did it happen?
2. Do you think you found a specific place in the code where the bug is at?

This error happened to me a couple of times in the past because of bugs in the binance-java-sdk or connection problems.
I will check if this could have been caused by the sdk and I will appreciate if you try to run the bot again and let me know if it worked or not.

Kind regards,

Yonathan

**Comment by gizmobin** [comment]
Yes, it happens every time I run the code.   I even cleared all my folders and rebuild the project with a fresh download.  I downloaded the zip, not a git clone, perhaps I will try that in case somehow there is something in the zip causing issues.

I traced the code all the way down to the okHttp connect but didn't see anything that looked out of place.  I didn't see anything that would allow me to output any handshakes or debug type details for the connection.   

I just ran it again and did get the same result.  I may also try this on my laptop to see if it is local to my machine.  I am running the code in IntelliJ on Windows 10 

If there is anything that you would like me to try please let me know.  I'll let you know if I am able to uncover anything.

thanks.
